### ISSUE TITLE
Update num_enum_derive syn dependency to syn 2

### ISSUE THREAD

**Issue by jtroo** [illicitonion/num_enum#111]
Syn 2 was released recently and some crates, e.g. thiserror, are already migrated. To reduce clean compile times, should upgrade dependency to syn 2.

**Comment by jtroo** [comment]
Thanks for the work on this! Looks like PRs have been merged.

Requesting a `cargo publish` so I can update my deps v2 - when you get a chance.

**Comment by illicitonion** [comment]
I just published v0.6.0 - thanks!
