### ISSUE TITLE
rust-analyzer lint issue with derived macro code

### ISSUE THREAD

**Issue by westy92** [illicitonion/num_enum#122]
I have the following code:

```rust
#[derive(TryFromPrimitive)]
#[repr(u16)]
enum Size {
    Small,
    Medium,
    Large,
}
```

`rust-analyzer` gives me the following warning:
<img width="905" alt="image" src="https://github.com/illicitonion/num_enum/assets/290167/319edc55-179b-4d86-86da-bb71f8b84888">

I found the code where [this name is defined](https://github.com/illicitonion/num_enum/blob/main/num_enum_derive/src/lib.rs#L285) and  can change it to `{}_NUM_ENUM_{}_`, but I don't see a way to transform `info.ident` into UPPERCASE.

**Comment by illicitonion** [comment]
Thanks for the bug report!

This is interesting... We explicitly `allow` this lint where we're generating this code: https://github.com/illicitonion/num_enum/blob/bf70f0a7f2b8601a2bcdcb1ab459a2195cb57030/num_enum_derive/src/lib.rs#L793

So this feels like possibly a rust analyzer bug where it's not properly applying the `allow` attribute to the containing block?

Note: We use an inner attribute, so this should apply to the entire block; I wonder if it's just not handling inner attributes properly, and if this change to num_enum_derive would work around the bug:

```diff
diff --git a/num_enum_derive/src/lib.rs b/num_enum_derive/src/lib.rs
index 8629106..498218b 100644
--- a/num_enum_derive/src/lib.rs
+++ b/num_enum_derive/src/lib.rs
@@ -790,9 +790,9 @@ pub fn derive_try_from_primitive(input: TokenStream) -> TokenStream {
             > {
                 // Use intermediate const(s) so that enums defined like
                 // `Two = ONE + 1u8` work properly.
-                #![allow(non_upper_case_globals)]
                 #(
                     #(
+                        #[allow(non_upper_case_globals)]
                         const #expression_idents: #repr = #variant_expressions;
                     )*
                 )*
```

I'm also curious if this is somehow related to RA's handling of macros or more general - do you see the same result if you replace the macro call with the output of calling `cargo expand` on the code?

**Comment by 0xflick** [comment]
I ran into the same thing. I think it's an analyzer issue. Patching `num_enum` with the change above caused `cargo build` to output the warnings (previously it was just analyzer inside my editor). Replacing the code with the output of `cargo expand` got rid of the warnings completely.

**Comment by illicitonion** [comment]
This looks like https://github.com/rust-lang/rust-analyzer/issues/6541 :)

**Comment by sunmy2019** [comment]
I reported it here. https://github.com/rust-lang/rust-analyzer/issues/15344

**Comment by sunmy2019** [comment]
Upstream has fixed this issue

**Comment by illicitonion** [comment]
Great news, thanks! for the update!
