### ISSUE TITLE
Upgrade to `proc-macro-crate 2`

### ISSUE THREAD

**Issue by MarijnS95** [illicitonion/num_enum#133]
Hey! I'm currently going through a dependency chain to resolve some duplicates of `toml` and the `toml_edit` crates, and one of which is solved by `proc-macro-crate 2` bumping these dependencies:

https://github.com/bkchr/proc-macro-crate/commit/39a7c1844fc4d73ef397a7e8d9419f1f3381aa44

How easy/trivial (and MSRV-compliant) would it be for `num_enum_derive` to bump to this crate release? It looks like `metadata_checks` depends on an older `cargo_toml` as well which has the `toml` dependency.

**Comment by illicitonion** [comment]
Hello! Very reasonable request! As you've noted, this is currently pretty hard for MSRV reasons, and jumping forwards 14 months would be a pretty large jump...

One thing worth mentioning is that `proc-macro-crate` is an optional dep, and it's only useful at all if you've renamed `num_enum` in your dep tree (which is _very_ unusual to do). Would just disabling the optional dep help your situation?

**Comment by MarijnS95** [comment]
Unfortunately optional deps will show up as part of `Cargo.lock` and will afaik get picked up by `cargo-deny`, even if they're not (always) active :/

At least good to know that it doesn't get compiled/used by default.

**Comment by illicitonion** [comment]
This was hopefully fixed in https://github.com/illicitonion/num_enum/pull/134 which was released in 0.7.1
