### ISSUE TITLE
Missing tag for 0.7.1

### ISSUE THREAD

**Issue by rdelfin** [illicitonion/num_enum#138]
It looks like 0.7.1 was already released in crates.io but there's no corresponding git tag. Any chance you could add it?

**Comment by illicitonion** [comment]
Oops, thanks for the heads up - I've just pushed the tag.

I should probably get around to automating releases at some point... :)

**Comment by rdelfin** [comment]
Thanks! I have a github workflow [here](https://github.com/rdelfin/min-review-bot/blob/main/.github/workflows/release.yaml) that does auto-tagging and pushing bumps if that's something you'd like to use :smile:
