### ISSUE TITLE
Multiple alternative primitives per variant

### ISSUE THREAD

**Issue by regexident** [illicitonion/num_enum#22]
In some binary protocols (a common use-case for **num_enum**) the number of defined enum values is less than the number of possible values in the backing bitfield.

As such one might have a 3-bit value that maps to only 5 enum variants, with the highest variant acting as kind of a wildcard to avoid undefined behavior when using the type.

The popular [BMP280](https://www.bosch-sensortec.com/products/environmental-sensors/pressure-sensors/pressure-sensors-bmp280-1.html) pressure sensor by BOSCH makes use of such mapping in its `osrs_t` and `osrs_p` registers:

| Value               | Meaning          |
| ------------------- | ---------------- |
| `000`               | Skipped          |
| `001`               | 1× Oversampling  |
| `010`               | 2× Oversampling  |
| `011`               | 4× Oversampling  |
| `100`               | 8× Oversampling  |
| `101`, `110`, `111` | 16× Oversampling |

For such types it would be nice to be able to specify alternative values:

```rust
#[derive(Eq, PartialEq, Copy, Clone, Debug, IntoPrimitive)]
#[repr(u8)]
pub enum Oversampling {
    /// Do not sample
    Off = 0b000,
    /// Return average of 1 sample
    Oversample1X = 0b001,
    /// Return average of 2 samples
    Oversample2X = 0b010,
    /// Return average of 4 samples
    Oversample4X = 0b011,
    /// Return average of 8 samples
    Oversample8X = 0b100,
    /// Return average of 16 samples
    #[num_enum(alternative(0b110, 0b111))]
    Oversample16X = 0b101,
}
```

As such `try_from()` would map the values `0b101`, `0b110`, and `0b111` onto `Oversampling::Oversample16X`,  
while `into()` would always produce the canonical value `0b101`.

(Serde does something similar with its `#[serde(alias = "name")]` [attribute](https://serde.rs/variant-attrs.html#alias).)

---

@illicitonion would you in general be open to such an addition? If yes, then I might give it a try.

**Comment by illicitonion** [comment]
Thanks for the detailed description of the use-case!

I think this would be a fine addition to the library, and I like the example API you described. Another related feature could be to allow specifying a default which would be used for all other numbers; I'm imagining:
```rust
#[derive(Eq, PartialEq, Copy, Clone, Debug, FromPrimitive)]
#[repr(u8)]
pub enum Oversampling {
    /// Do not sample
    Off = 0b000,
    /// Return average of 1 sample
    Oversample1X = 0b001,
    /// Return average of 2 samples
    Oversample2X = 0b010,
    /// Return average of 4 samples
    Oversample4X = 0b011,
    /// Return average of 8 samples
    Oversample8X = 0b100,
    /// Return average of 16 samples
    #[num_enum(default)]
    Oversample16X = 0b101,
}
```

where trying to derive `FromPrimitive` without a default set would be an error.

I'd gladly review contributions that implemented either!

**Comment by regexident** [comment]
![both? both? both. both is good.](https://media.giphy.com/media/hM9zK1qvsrwek/giphy.gif)

👉🏻 [Added support for variant aliases and default variants #23](https://github.com/illicitonion/num_enum/pull/23)
