### ISSUE TITLE
Add an associated `Error` type to `TryFromPrimitive`

### ISSUE THREAD

**Issue by illicitonion** [illicitonion/num_enum#25]
The `TryFromPrimitive` implementation of  added as part of `FromPrimitive` which was added in #23 returns a `Result<_, TryFromPrimitiveError>` even though it's infallible.

Instead, we should probably give `TryFromPrimitive` an associated `Error` type, which will be `TryFromPrimitiveError` for `#[derive(TryFromPrimitive)]` and `std::convert::Infallible` for `#[derive(FromPrimitive)]`.

We didn't do this in #23 because it would be a breaking change, but next time we happen to be doing a breaking change release, we should tack this on too.

**Comment by recatek** [comment]
Would it make sense to add a conversion to std::num::TryFromIntError, to work with generic code that already handles TryFrom<> conversion failure from other types?

**Comment by illicitonion** [comment]
`FromPrimitive` no longer implements `TryFromPrimitive`, so I think this issue is no longer relevant.
