### ISSUE TITLE
TryFromPrimitive: failed to resolve: could not find `result` in `core`

### ISSUE THREAD

**Issue by stijnfrishert** [illicitonion/num_enum#27]
Whenever I try to derive my enum from `TryFromPrimitive`, I get the following error:

```
failed to resolve: could not fine `result in `core`
```

Here's my enum:

```
#[derive(Debug, Eq, PartialEq, IntoPrimitive, TryFromPrimitive)]
#[repr(u8)]
enum Error {
    InvalidString,
    InvalidPointer,
    CouldNotLoadFile,
    CouldNotCreateFile,
    JsonReadError,
    JsonWriteError,
}
```

I've got my own module named `core`, so could this be some sort of name clash?

(I assume it's idiomatic not to use `use` statements in macro expansions? Pretty new to macro's)

**Comment by danielhenrymantilla** [comment]
> I've got my own module named core, so could this be some sort of name clash?

It could very well be one, but I've locally tested it and cannot encounter that issue with the latest `num_enum`. Can you try running `cargo update -p num_enum` and see if the error persists?

  - If so, make sure you use the latest `num_enum` dependency by updating the version number appearing in the `Cargo.toml` file. If you have [`cargo-edit`](https://crates.io/crates/cargo-edit) installed, you can achieve this by simply running `cargo upgrade num_enum`.

**Comment by stijnfrishert** [comment]
Hmm, I added `num_enum` to my toml today with the crates.io copy (`0.5.1`), but I ran your both commands just in case and it's still happening.

I just ran `cargo expand`, maybe that helps? I don't see any `use` statements besides my own. I'm not sure what's failing here, but maybe it rings a bell with you?

```
use core::{
    event::{graph::Graph, Event},
    song::Song,
};
use graphql::{execute, Context};
use num_enum::TryFromPrimitive;
use ref_cast::RefCast;
use std::{
    cell::RefCell,
    cmp::min,
    ffi::CStr,
    fs::File,
    os::raw::{c_char, c_int, c_uchar, c_uint, c_void},
    slice,
};
#[repr(u8)]
enum Error {
    InvalidString = 0,
    InvalidPointer = 1,
    CouldNotLoadFile = 2,
    CouldNotCreateFile = 3,
    JsonReadError = 4,
    JsonWriteError = 5,
}
impl ::num_enum::TryFromPrimitive for Error {
    type Primitive = u8;
    const NAME: &'static str = "Error";
    fn try_from_primitive(
        number: Self::Primitive,
    ) -> ::core::result::Result<Self, ::num_enum::TryFromPrimitiveError<Self>> {
        #![allow(non_upper_case_globals)]
        const InvalidString__num_enum_0__: u8 = 0;
        const InvalidPointer__num_enum_0__: u8 = 1;
        const CouldNotLoadFile__num_enum_0__: u8 = 2;
        const CouldNotCreateFile__num_enum_0__: u8 = 3;
        const JsonReadError__num_enum_0__: u8 = 4;
        const JsonWriteError__num_enum_0__: u8 = 5;
        #[deny(unreachable_patterns)]
        match number {
            InvalidString__num_enum_0__ => ::core::result::Result::Ok(Self::InvalidString),
            InvalidPointer__num_enum_0__ => ::core::result::Result::Ok(Self::InvalidPointer),
            CouldNotLoadFile__num_enum_0__ => ::core::result::Result::Ok(Self::CouldNotLoadFile),
            CouldNotCreateFile__num_enum_0__ => {
                ::core::result::Result::Ok(Self::CouldNotCreateFile)
            }
            JsonReadError__num_enum_0__ => ::core::result::Result::Ok(Self::JsonReadError),
            JsonWriteError__num_enum_0__ => ::core::result::Result::Ok(Self::JsonWriteError),
            #[allow(unreachable_patterns)]
            _ => ::core::result::Result::Err(::num_enum::TryFromPrimitiveError { number }),
        }
    }
}
impl ::core::convert::TryFrom<u8> for Error {
    type Error = ::num_enum::TryFromPrimitiveError<Self>;
    #[inline]
    fn try_from(
        number: u8,
    ) -> ::core::result::Result<Self, ::num_enum::TryFromPrimitiveError<Self>> {
        ::num_enum::TryFromPrimitive::try_from_primitive(number)
    }
}
```

**Comment by stijnfrishert** [comment]
Moreover, when I try to `use ::core::result;` myself in the file, I get the same error. Maybe you're not just allowed to use `core` as a name for your custom module (though I've seen other projects do it)?

**Comment by danielhenrymantilla** [comment]
> Moreover, when I try to use ::core::result; myself in the file, I get the same error.

Oh! Are you using the `2018` edition? (`edition = "2018"` in the `Cargo.toml` file)

**Comment by stijnfrishert** [comment]
Yeap, I am! How does that make a difference (I'm relatively new to Rust)?

**Comment by danielhenrymantilla** [comment]
🤔 using the 2018 edition should have been fine

  - it makes a difference in that it changes the meaning of `::some_name` means: in edition `2018`, it unambiguously refers to an (external) crate named `some_name` (hence avoiding a name clash with some `mod core` that one may have (and that you do have)), whereas in the older (2015) edition, it referred to some item located at the root of the crate (which would be written as `crate::some_name` if using the 2018 notation).

    And since the macro emits a `::core::...` path, expecting to refer to the `core` crate, it is important that the edition 2018 be used.

___

Since I have been unable to diagnose / guess where the problem comes from, would you be able to setup some kind of minimal gist or repo featuring the error?

**Comment by stijnfrishert** [comment]
Aaaah, but wait. My `core` isn't a module, but a separate crate in the same repo! So I guess `::core::...` refers to that, instead of the standard's `core`.

I guess the better way to go about it is to just rename my own `core` sibling crate, I guess?

**Comment by danielhenrymantilla** [comment]
Yes, having `::core` refer to something that is not the `core` library is not supported.

  - @illicitonion do you think we should support that? It's mainly a matter of `pub use` re-exporting `::core` from `num_enum`, and replacing all our emitted references with `::num_enum::core`.
    Functionality-wise, it wouldn't change much, except for supporting this use case, but it would hinder a bit the `cargo expand` readability.
    Maybe gate that under a `fully-qualified-paths` optional feature flag?

**Comment by illicitonion** [comment]
It feels like having your own crate named `core` is:
* Probably a pretty bad idea
* Pretty niche
* Easy to avoid

So I'm inclined to say let's leave this unsupported and recommend anyone who runs into this in the future renames their crate.

I wouldn't strongly object to adding an optional feature, but it feels like the burden of needing to test this in the future, and generally be aware of it when making changes, probably doesn't merit the value the support would bring.

**Comment by stijnfrishert** [comment]
I would agree here. In hindsight it seems like a weird thing to do, and it's not too much work to find another fitting name for my own crate.

So yes, I'd be fine with leaving it at that. :)
I guess it's up to the both of you if you want to sink in the time for a feature, then.

Thanks for helping out!

**Comment by danielhenrymantilla** [comment]
Ok then, we'll be closing it, but if somebody feels like they have a motivating example to justify re-opening it, feel free to post a comment saying so.
