### ISSUE TITLE
Why default on TryFromPrimitive ?

### ISSUE THREAD

**Issue by Stargateur** [illicitonion/num_enum#31]
I see no point of implement default for TryFromPrimitive, FromPrimitive will avoid the need to check for error, and default make TryFromPrimitive impossible to have error anyway so, it's just better to use FromPrimitive in this case. Or I'm missing something.

It would make sense if default is ignored by TryFromPrimitive, and make TryFromPrimitive compatible with FromPrimitive, making the user choice if to ignore or not default value.

**Comment by danielhenrymantilla** [comment]
Similar to what was mentioned at [the related issue](https://github.com/illicitonion/num_enum/issues/32#issuecomment-717358966),

I think the solution here would be to add more special syntax to disambiguate:

So the solution here is to have an even more verbose syntax:

```rust
#[derive(Debug, Eq, PartialEq, FromPrimitive, TryFromPrimitive)]
#[repr(u8)]
enum MyLittlePony {
    Sparkle = 0,
    //        this can be added to specify the alternatives only apply to `FromPrimitive`
    //        vvvvvvvvvvvvvvv
    #[num_enum::FromPrimitive(default)]
    Dash = 1,
}

fn main ()
{
    assert_eq!(
        MyLittlePony::try_from(1_u8),
        Ok(MyLittlePony::Sparkle),
    );
    assert!(matches!(
        MyLittlePony::try_from(2_u8),
        Err(_),
    ));
}
```
