### ISSUE TITLE
How to return any TryFromPrimitiveError from a function? (Or, how to impl `From` any TryFromPrimitiveError)

### ISSUE THREAD

**Issue by joaopaulobdac** [illicitonion/num_enum#71]
Hey, I'm new to Rust. Is it possible to convert any `TryFromPrimitiveError`s into a single error (something like `EnumError(TryFromPrimitiveError<E>)`)? I'm using `map_err` everywhere and it's horrible.

**Comment by danielhenrymantilla** [comment]
Would https://docs.rs/num_enum/0.5.6/num_enum/derive.FromPrimitive.html#turning-a-primitive-into-an-enum-with-from suit your use-case?

**Comment by joaopaulobdac** [comment]
It would be better to return early with an Err after an unknown variant is found, but I think I can work with this too. Thanks for the tip!

**Comment by danielhenrymantilla** [comment]
Ah, ok, in that case, you could try to write a more general _generic_:

```rs
impl<Enum: TryFromPrimitive> From<TryFromPrimitiveError<Enum>> for YourError {
    fn from(err: TryFromPrimitiveError<Enum>) -> Self {
        /* the contents of your current `.map_err()` */
    }
}
```
