### ISSUE TITLE
TryFromPrimitive incorrectly uses default attribute

### ISSUE THREAD

**Issue by ollie-etl** [illicitonion/num_enum#75]
If we have an enum where a `#[default]` is applied for another derive, `TryFromPrimitive` becomes useless, and will silently return the default. This is both undocumented, and makes no sense - surely the point of `TryFromPrimitive` is to test the input is valid. If the default is required, `FromPrimitive` has this behaviour documented.

```rust
#[derive(
    Debug,
    TryFromPrimitive,
)]
pub enum MyEnum {
    #[default]
    E1 = 1,
    E2 = 2,
}

assert_eq!(MyEnum::try_from(42).is_ok(),  "This passes!!!!")
```

Closely related to #31, however the fix there cannot be applied, because the attribute is actually required for another macro.

**Comment by illicitonion** [comment]
Sorry for the super slow response here - yes, I agree that `TryFromPrimitive` should probably ignore `default` attributes completely, and only `FromPrimitive` should pay attention to it. This will, however, be a breaking change, so we should probably bump to 0.6.0 with this change. I'll put together a PR soon.
