### ISSUE TITLE
Why is UnsafeFromPrimitive not a trait like the rest?

### ISSUE THREAD

**Issue by ia0** [illicitonion/num_enum#78]
Is there a reason why the `UnsafeFromPrimitive` derive macro doesn't implement the following trait rather than create an associated function?

```rust
pub trait UnsafeFromPrimitive: Sized {
    type Primitive: Copy + Eq;
    unsafe fn from_unchecked(number: Self::Primitive) -> Self;
}
```

**Comment by illicitonion** [comment]
No good reason not to - feel free to send over a PR if you have a reason to want a trait here!

**Comment by ia0** [comment]
Yes, I'm writing generic code over enums and I want to call `from_unchecked`. I created #79.
