### ISSUE TITLE
Hierarchical enums using arbitrary enum discriminants

### ISSUE THREAD

**Issue by hecatia-elegua** [illicitonion/num_enum#81]
Relevant issue: https://github.com/rust-lang/rust/issues/60553

I am currently working on a PCI driver with many predefined values for classes and their subclasses:
```rs
enum ClassCode {
    Old(Old) = 0x0,
    MassStorage(MassStorageController) = 0x1,
    Network(NetworkController) = 0x2,
//...
enum MassStorageController {
    SCSI(SCSIController) = 0x0,
    IDE(IDEController) = 0x1,
    FloppyDiskController = 0x2,
//...
enum SCSIController {
    VendorSpecific = 0x00,
    StorageDevice = 0x11,
//...
```
As you can see, these form a kind of hierarchy.
Now I would want to parse the raw values from pci into an enum-value of type `ClassCode`.

This would allow for a very nice API:
```rs
for device in pci::pci_device_iter() {
    match device.class {
        ClassCode::MassStorage(MassStorageController::SCSI(_)) => //...
        ClassCode::Network(_)  => //...
    }
}
```

**Comment by hecatia-elegua** [comment]
Implementation-wise I'm not quite sure how to handle it, as we first need to know the variant of `ClassCode` before invoking the next deeper try_from.
It could be done by always filling the deeper values with their lowest available variant and ignoring deeper values in the final matching:
```rs
//example, ClassCode try_from
match value {
    0x1 => ClassCode::MassStorage(MassStorageController::SCSI(SCSIController::VendorSpecific))
    //...
}

//then putting it together:
match ClassCode::try_from_primitive(class)? {
    ClassCode::MassStorage(_) => match MassStorageController::try_from_primitive(subclass)? {
        MassStorageController::SCSI(_) =>match SCSIController::try_from_primitive(subsubclass)? {
            SCSIController::StorageDevice => ClassCode::MassStorage(MassStorageController::SCSI(SCSIController::StorageDevice))
        }
    }
    //...
}
```
Wow, that looks bad.
Maybe instead we should do:
```rs
ClassCode::try_from_primitive_tree([class, subclass, subsubclass]).unwrap()
```
with the `try_from_primitive_tree` argument being generic and then, in pseudo-code:
```
value1, value2, value3
ClassCode[value1] -> identifier = MassStorage, contains MassStorageController, so call its try_from_primitive_tree

value2, value3
MassStorageController[value2] -> identifier = SCSI, contains SCSIController, so call its try_from_primitive_tree

value3
SCSIController[value3] -> identifier = StorageDevice, contains nothing/is last value, so done, return
```

**Comment by hecatia-elegua** [comment]
Any input on this, now that `arbitrary_enum_discriminant` is stabalized?

**Comment by illicitonion** [comment]
Sorry for the delay in getting back to you on this one.

This seems like very specific behaviour, and I'm not sure how general it is... I also don't fully follow the examples, though, so it could be that I'm just not following.

Is there some fixed relationship between the outer and inner enums? Or is the situation that the inner-most enums all have uniquely specified discriminants, each of the inner enums may only appear in exactly one outer enum, and we should just pick whichever outer enum happens to be allowed to contain the inner enum?

Could you point at some real-world code which is currently being manually written, and give some example inputs and how they map to outputs?

**Comment by hecatia-elegua** [comment]
Got something to work with: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4d908d6aeb29c1961524bb5b5275b4df

**Comment by illicitonion** [comment]
I think this feels like pretty special-case behaviour that probably warrants its own independent implementation outside of this crate. I don't think there's an obvious unique mapping from raw values to a hierarchy of enum values here, so I'd suggest writing a new macro which may use the `TryFrom`/`From` implementations generated by this one, and build on top of them.
